# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

pool: Default
name: $(BuildDefinitionName)_$(Year:yyyy).$(Month).$(DayOfMonth)$(Rev:.r)

variables:
- group: JFrog
- name: solution 
  value: '**/*.sln'
- name: buildPlatform
  value: 'Any CPU'
- name: buildConfiguration
  value: 'Release'



steps:
- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    projects: '**/VideoTranslate.WebAPI.csproj'
  displayName: 'Restore Nuget Packages'

- task: DotNetCoreCLI@2
  inputs: 
    command: 'build'
    projects: '**/VideoTranslate.WebAPI.csproj'
    arguments: '--no-restore' 
  displayName: 'Build projects'

#- task: DotNetCoreCLI@2
#  inputs:
#    command: 'test'
#    projects: '**/*Test.csproj'
#    arguments: '--no-restore --no-build'
#  displayName: 'Run Tests'

- task: DotNetCoreCLI@2
  inputs:
    command: 'pack'
    packagesToPack: '**/VideoTranslate.Shared.csproj'
    nobuild: false
    versioningScheme: 'byBuildNumber'
    packDirectory: '$(Build.ArtifactStagingDirectory)/Shared'
  displayName: 'Pack Shared Project'

# - task: DotNetCoreCLI@2
#   inputs:
#     command: 'push'
#     packagesToPush: '$(Build.ArtifactStagingDirectory)/Shared/*.nupkg'
#     nuGetFeedType: 'external'
#     publishFeedCredentials: 'videoTranslate Nuget Artifactory'
#   displayName: 'Push Shared Project to Artifactory'
  
# - task: DotNetCoreCLI@2
#   displayName: Push Nuget Package
#   inputs:
#     command: custom
#     custom: nuget
#     arguments: >
#       push $(Build.ArtifactStagingDirectory)/Shared/*.nupkg
#       -s $(JFrog-VideoTranslate)
#       -k $(JFrog-Username):$(JFrog-Password)
#   displayName: 'Push Shared Project to Artifactory'

- task: CmdLine@2
  inputs:
    script: 'dotnet nuget push $(Build.ArtifactStagingDirectory)/Shared/*.nupkg --source $(JFrog-VideoTranslate) --api-key $(JFrog-Username):$(JFrog-Password)'
  displayName: 'Push Shared Project to Artifactory'

- task: CmdLine@2
  inputs:
    script: 'systemctl stop videoTranslate.service'
  displayName: 'Stop WebAPI'

- task: CopyFiles@2
  inputs:
    SourceFolder: '/usr/share/videoTranslateWebApi'
    Contents: '**'
    OverWrite: true
    TargetFolder: '/usr/share/backup_videoTranslateWebApi'
  displayName: 'make a backup'

- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: '**/VideoTranslate.WebAPI.csproj'
    arguments: '--configuration $(buildConfiguration) --no-restore'
    modifyOutputPath: false
  displayName: 'Publish VideoTranslate'

- task: ExtractFiles@1
  inputs:
    archiveFilePatterns: '**/publish.zip'
    destinationFolder: '/usr/share/videoTranslateWebApi'
    cleanDestinationFolder: true
    overwriteExistingFiles: true
  displayName: 'Copy published files into Production folder'

- task: CmdLine@2
  inputs:
    script: 'systemctl start videoTranslate.service'
  displayName: 'Start WebAPI'

