# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main

pool: Default

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    projects: '**/VideoTranslate.DbUpdate.csproj'
  displayName: 'Restore Nuget Packages'

- task: DotNetCoreCLI@2
  inputs: 
    command: 'build'
    projects: '**/VideoTranslate.DbUpdate.csproj'
    arguments: '--no-restore' 
  displayName: 'Build projects'

- task: DotNetCoreCLI@2
  inputs:
    projects: '**/VideoTranslate.DbUpdate.csproj'
    command: 'run'
  displayName: ' ( ⊙…⊙) Run DbUpdate (⊙…⊙ )'